### ISSUE TITLE
When window height is shorter than menu, menu cannot scroll

### ISSUE THREAD

**Issue by timothystock** [ymc-thzi/mobile-menu-hamburger#3]
Hi there, 
I've implemented this on a test site and there seems to be an issue when a mobile device is turned on its side (landscape mode) and the vertical height of the view is restricted, that the menu itself is unable to scroll. This happens on your demo site as well as my own test (not on public domain). 

I'm going in search of another off-screen nav, so there's no timescales here - just thought you'd like to be made aware of it for future fixes. 

I think it's something to do with the z-indexing, and opacity used to hide it. It works fine on desktop browsers (when you reduce the window height, a scroll bar becomes available) but not on mobile browsers (ie where it would be required to have an overflow:scroll).

Thanks in advance,

**Comment by shortland** [comment]
What are the screen dimensions? (what device are you using?)
Working fine for me on iPhone 6, iPhone 5, iPad 2, iPad 4 @timothystock

**Comment by timothystock** [comment]
This issue is prevalent on iPhone 5 and 6 (tested by myself). Have switched
to a different system now, but would appreciate if there are any fixes etc.
Not sure why it would be working for you and not me but indefinitely didn't
work for me and thought (when I researched the issue) that others had also
found this bug - what did you do to fix this?

Tim

On Thursday, June 11, 2015, Ilan Kleiman <notifications@github.com> wrote:

> What are the screen dimensions? (what device are you using?)
> Working fine for me on iPhone 6, iPhone 5, iPad 2, iPad 4 @timothystock
> <https://github.com/timothystock>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ymc-thzi/mobile-menu-hamburger/issues/3#issuecomment-110952569>
> .
>


-- 
Tim Stock

[e] timothystock@gmail.com <timothystock@googlemail.com>
[m] +44(0)7706 440 492
[w] http://www.timstock.co.uk

**Comment by shortland** [comment]
@timothystock Just making sure: You're saying that you can't see all the menu items while in landscape mode because they get cut off right? And you're unable to scroll in the menu to see them?

I'm not sure why; but that was intentional by @ymc-thzi 
Lines 31-33 have this code:
```
        jQuery('#container').bind('touchmove', function (e) {
            e.preventDefault()
        });
```

It prevents scrolling on mobile devices when the menu is open - which would be why you're unable to scroll.

You can either remove the code, or rather than selecting the id 'container', you can select the contentLayer instead.

ie:
```
        jQuery('#contentLayer').bind('touchmove', function (e) {
            e.preventDefault()
        });
```

This <strong>should</strong> allow scrolling on the menu, but still disable it for the page.
It is a bit buggy though... Scrolling over at the end and before the menu will cause the contentLayer to scroll when it's not supposed to (at least for me), it "works", but is still quite a bit ugly to deal with.

My ugly fix:
line 31-36
```
        jQuery('#content').bind('touchmove', function (e) {
            e.preventDefault()
        });
        jQuery('#contentLayer').bind('touchmove', function (e) {
            e.preventDefault()
        });
```
line 50-51
```
        jQuery('#content').unbind('touchmove');
        jQuery('#contentLayer').unbind('touchmove');
```

Including that "content" not scroll either - since in normal portrait mode; simply having contentLayer seems to mess it up.

**Comment by ymc-thzi** [comment]
thx for your engagement. The reason for disabling all scrolling is that the menubar will end with the page-height and scolling down will show that end of the container.
So yes I know it's ugly but unless I'll fix that and push the solution I have to say this feature (scrollable opended menubar) is not supported.
